# Generated by Django 5.1 on 2024-08-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employes'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
