# Generated by Django 5.1 on 2024-08-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_number', models.PositiveSmallIntegerField()),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emp_chair', to='main.employee')),
            ],
            options={
                'verbose_name_plural': 'Chair',
                'db_table': 'chair',
            },
        ),
    ]
