# Generated by Django 5.1 on 2024-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='SmartShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color_id', models.ManyToManyField(to='main.color')),
            ],
            options={
                'verbose_name_plural': 'SmartShoes',
                'db_table': 'smart_shoes',
            },
        ),
    ]
